### ISSUE TITLE
My mouse go in the top right corner of the screen

### ISSUE THREAD

**Issue by Drayecos** [Zurek0x/NuremX#11]
Hello, thanks for you great work, i following every step, but I have one problem. When I put the key "X" for aimbot after F2 my mouse go in the top right corner of the screen. I think the problem comes from the following parameter :

[settings]
welcome_notif = 1
size_of_window = 1000
confidence_threshold = 0.34
nms_iou = 0.34
mouse_delay = 0.0001
pixel_increse = 10
status_overlay = 1
overlay_resolution_X = 30
overlay_resolution_Y = 30
promote = 0

For information I play in 3440x1440 or 1920 x 1080 without fullscreen with low video parameters. I deleted all my other overlays but I still have the same problem.

Config 3080 rtx
Proc : Ryzen 3900x

Please help

**Comment by Drayecos** [comment]
Same problem with resolution 1920 x 1080

**Comment by kakahost** [comment]
Ooooh, same problem on 1280x1024

**Comment by Drayecos** [comment]
Try with this resolution 1920 x 1080, because this project was planned for this resolution

**Comment by Zurek0x** [comment]
I will be closing this issue due to no response.
