### ISSUE TITLE
Can someone please help me?

### ISSUE THREAD

**Issue by mastermain0524** [Zurek0x/NuremX#12]
Hello, brother!
I get this error when I run run.bat.

Traceback (most recent call last):
  File "NuremX.py", line 225, in <module>
    main()
  File "NuremX.py", line 127, in main
    start_collect.start()
  File "C:\Users\username\Desktop\NuremX-main\open-source\lib\aimbot.py", line 188, in start
    crosshair_dist = math.dist((relative_head_X, relative_head_Y), (self.box_constant/2, self.box_constant/2))
AttributeError: module 'math' has no attribute 'dist'

I didn't modify anything.
Why can't I use dist... 
I know this may be a basic question, but I'd be glad to get some help.

**Comment by VeryBigSad** [comment]
You sure you have the right python version, 3.9 or above? You can check this by typing `python --version` in cmd/powershell

**Comment by mastermain0524** [comment]
Sorry my bad & Thank you so much!!!
Can I rewrite the settings for this program?
1. work while holding down right click and holding down left shift
2. make the Aim position not just the head
Please let me know the part to be rewritten and what it is.
Sorry if my English is not understood.

**Comment by VeryBigSad** [comment]
Not currently at my workstation so I can't make a PR, but it seems you would have to edit [this line](https://github.com/Zurek0x/NuremX/blob/b87064fc75b42d4061d5e8b855f8a2d8b5535e2d/open-source/lib/aimbot.py#L184) to alter the calculation of the head.
As for left shift, [here](https://github.com/Zurek0x/NuremX/blob/b87064fc75b42d4061d5e8b855f8a2d8b5535e2d/open-source/lib/aimbot.py#L120) change 0x58 to whatever key code you want (currently it appears to me that the key is set to X)

**Comment by mastermain0524** [comment]
Thank you brooooo!!!
I can do this!
When I try to play in full screen, APEX is on the back.
Can this only be done in borderless window mode?
