### ISSUE TITLE
When I run setup Bat.

### ISSUE THREAD

**Issue by Krazyyysa** [Zurek0x/NuremX#2]
![image](https://user-images.githubusercontent.com/88943241/166680295-16620c5d-c8d6-4542-bf89-de1dc68a2b4b.png)

**Comment by Krazyyysa** [comment]
Hello, brother! I how to solve this problem.

**Comment by Zurek0x** [comment]
Hello! Thank you for submitting your issue!
You can try to install the Open-Source PyTorch version using the command below.
`pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`
This is for Windows 10 on Cuda Version 11.3.

After installing this package just remove the line _**torch==1.11.0+cu113**_ from **_requirements.txt_** file.
And then re-run the setup for the Requirements.txt file with command below
`pip install -r requirements.txt`

**Comment by Zurek0x** [comment]
Try using CONDA or PIP to install the required library from the PyTorch website.
`https://download.pytorch.org`
Go to the download section and select PyTorch/Torch Version _**CUDA 1.13**_ and use the command it gives you.

**Comment by Zurek0x** [comment]
I am going to close this issue as it appears you have resolved the issue, If you would like to re-open this issue you may do so.
