### ISSUE TITLE
I don't know how to do it and it doesn't run successfully

### ISSUE THREAD

**Issue by 651699976** [Zurek0x/NuremX#21]
The first contact, based on the tutorial, but never ran successfully, I was very confused

**Comment by Zurek0x** [comment]
Figure it out, This wasn't made for script kiddies, You just now created a github account to commend that which makes me believe that you have no knowledge with python or programming in general, If you can't install a library and run the code that is your problem and isn't a issue with the code.

Learn what to do before you start bitching.
