### ISSUE TITLE
My friend has an problem

### ISSUE THREAD

**Issue by kakahost** [Zurek0x/NuremX#7]
When he plays Apex, his movement do only after 2 seconds. He solved it, but here is a new problem. In Apex, his overlay shows 1 FPS ad his aimbot makes broken. In overlay window, he see 20 FPS. Here is a problem: How to make overlay FPS while in Apex more?

**Comment by Zurek0x** [comment]
The only way to improve FPS is either by Lowering your game graphics too lower the load on the GPU & CPU or upgrade your components, Like I said, This cheat is very hardware demanding.
