### ISSUE TITLE
1280x1024 aimbot problem

### ISSUE THREAD

**Issue by kakahost** [Zurek0x/NuremX#8]
[settings]
welcome_notif = 1
size_of_window = 266
confidence_threshold = 0.55
nms_iou = 0.55
mouse_delay = 0.0001
pixel_increse = 5
status_overlay = 1
overlay_resolution_X = 10
overlay_resolution_Y = 10
promote = 0

When my friend running, my aimbot turns 90 degrees from him. He hasn't this problem. I have same settings as he. Is it my monitor resolution problem? And how to solve it?

**Comment by Zurek0x** [comment]
It may be your monitor, The cheat is built for 1920x1080 We never planned to have it run on 1280x1024.
I can't give too much info on it other then you will just have to tweak the settings for yourself.

We will take this into consideration though and put this into our error-logs too add Multi-Resolution support with documentation on it, Sorry.

**Comment by kakahost** [comment]
How long may we wait for custom resolution support?

**Comment by Zurek0x** [comment]
> How long may we wait for custom resolution support?

I cannot say as the development and updates have been a little slow lately, When we do update the project next we will do some testing, I am no longer interested in these kinds of projects anymore so the next update won't be for awhile.
