### ISSUE TITLE
There was a problem running nuremx.py

### ISSUE THREAD

**Issue by Aleax2016** [Zurek0x/NuremX#9]
Hi, brother, I have installed PIP and python, but run nuremx Py prompts these questions. What is the problem? How to solve it, brothe
![111](https://user-images.githubusercontent.com/19349931/173220795-485fe1ae-9138-478c-a769-5e7c1d2963c6.png)
r

**Comment by kakahost** [comment]
Did you install pip into PATH?

**Comment by Aleax2016** [comment]
yes,i install ，I ran this program, but the AIM-BOT did not work，Need a second monitor？

**Comment by kakahost** [comment]
No, you need an antivirus KHM... No, you need to be sure that enemy locking. Make sure about it in overlay window. If not, make sure that you enabled aimbot by pressing F2 after start and holding X.

**Comment by VeryBigSad** [comment]
> I succeeded in running the program. However, I am an AMD graphics card. Therefore, the running program only has 1fps. Is there yolov5 for AMD graphics card

Pretty sure the only way you can speed up your game here is either get an Nvidia GPU with cuda cores or run it on CPU, I might be wrong though
